[project]
name = "ai-mania"
version = "0.1.0"
description = "Guided project from Boot.Dev that teaches students how the AI tools they will be using on the job, actually work."
readme = "README.md"
requires-python = ">=3.14"
dependencies = ["google-genai==1.12.1", "python-dotenv==1.1.0"]
